org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.4.1
maven_group=io.github.tr100000
archives_base_name=researcher

# Dependencies
fabric_version=0.156.0+26.2
trutils_version=0.3.0+26.2
codec2schema_version=0.3.6+26.2
fzzy_config_version=0.7.6+26.2
modmenu_version=20.0.1

recipe_viewer=none
jei_version=30.15.0.104
rei_version=26.2.820
rrv_version=8.6.4+26.2

# Publishing
modrinth_extra_minecraft_versions=
